### ISSUE TITLE
Not working on CM 13

### ISSUE THREAD

**Issue by Logsogumadur** [andDevW/getChromium#11]
it doesn't work on Oneplus One, running CyanogenMod 13, with excellent wifi. When I open it and try to download I only see te message in the attachment, literally: "Alalysis error - Error during the analysis of the packet"

![2016-04-14 13 46 51](https://cloud.githubusercontent.com/assets/12232896/14531628/65461fe2-025e-11e6-9def-27b620b1d2bf.jpg)

**Comment by Primokorn** [comment]
Did you restrict some permissions? If not, a log should help.

**Comment by Logsogumadur** [comment]
No, there are no restrictions yet, and Privacy Guard is not enabled for this app.

ATTACHMENTS:
1. main screen of the app
2. log

![photo_2016-04-15_09-42-18](https://cloud.githubusercontent.com/assets/12232896/14554680/c47ff448-02ee-11e6-9f06-80bcc6ab6433.jpg)
[alogcat.2016-04-15-09-32-52+0200.txt](https://github.com/andDevW/getChromium/files/220528/alogcat.2016-04-15-09-32-52.0200.txt)

**Comment by Primokorn** [comment]
Not sure if andDevW can do something since the aim of this app is just to download Chromium.
You may want to try [those builds](http://forum.xda-developers.com/android/apps-games/unofficial-chromium-builds-arm-x86-t3355105).

**Comment by andDevW** [comment]
It could have to do with not wiping the cache partition after you installed CM. Seeing a lot of similar errors fixed by booting into recovery and selecting "wipe cache-partition" and "wipe dalvik partition".

**Comment by Logsogumadur** [comment]
It coud be that, in facts I didn't wipe it AFTER updating to the new CM.
As far as you know, will I lose all my data if I do it now?
I should give it a try.

**Comment by andDevW** [comment]
@Logsogumadur -No, it's 100% safe if you are very careful. Be sure and wipe ONLY **dalvik cache** and **cache** so it won't delete anything important.

**Comment by Logsogumadur** [comment]
It didn't work. Same error message.

**Comment by andDevW** [comment]
Two more possible solutions that come to mind:

**Wipe caches multiple times and reinstall getChromium**
1. Uninstall getChromium.
2. Boot into recovery, wipe dalvik cache x3 / wipe cache x3.
3. Select option to check/repair filesystem. 
4. Install getChromium.

**A 100% clean CM install**
1. Download the latest custom recovery(ie, https://dl.twrp.me/bacon/twrp-3.0.2-0-bacon.img.html), CAREFULLY verify the checksum to ensure that you have everything, and flash to your device.
2.  Download the latest CM "release" build , 
CAREFULLY verify the checksum to ensure that you have everything.
3. Backup EVERYTHING you want to keep/ eject any sdCard.
4. Wipe everything x 3 / Format everything x3 / Factory reset x3.
5. Select any option to check/repair filesystem.
6. Install the most recent "release" build of CM. 
7. Wipe dalvik cache x 3 / wipe cache x 3.
8.  Check Settings/Security/ -->  Unknown Sources 
9. Install getChromium.

**Comment by Logsogumadur** [comment]
it worked perfectly, great!

I'll also save your instructions to get a clean CM install, thanks.

**Comment by frazzmark** [comment]
On my phone it worked without having to wipe after install. I just used the latest cm13 nightly and twrp 3.0.0
