### ISSUE TITLE
**CYANOGENMOD/CUSTOM ROM ERRORS**

### ISSUE THREAD

**Issue by andDevW** [andDevW/getChromium#12]
**For any issues encountered while running ANY CUSTOM ROM:**

After any update or flash/reflash is advised to wipe both **dalvik cache** and **cache**.

If you are getting parse errors or getChromium is _not_ working correctly in _any way_,
 simply boot into recovery and select **wipe dalvik cache** and **wipe cache**. 

Be very careful **not** to wipe any of the other options listed.

Reboot back into your system and getChromium should work perfectly.

**Comment by BenjaminHCCarr** [comment]
Hi @andDevW I am running cyanogen Lollipop, I installed getChromium from FDroid, and get the error on downloading. I use TWRP, I wiped Dalvik and cache, rebooted to recovery, did it again for good measure, and no joy. If I download the APK on my own the file runs fine? I know it's "wontfix" but any clue what is going on? I am on Moto X 2014, and Moto/Lenovo abandoned my device, so for security I had to flash something else.

**Comment by andDevW** [comment]
If it's not a hardware defect of some kind then it's either a bad image or a bad recovery. 
Try installing the official CM recovery, then wiping the cache/dalvik cache. 
If that doesn't work, install a slightly different (newer or older) version of CM.
