### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by EMK2000** [andDevW/getChromium#14]
1. When I download the APK, please show the percentage of download progress, so that I know how much time approximately I need to wait. 
2. Option for automatically delete the downloaded APK and zip files after installing, so that I don't need to delete them manually every time. 
3. Showing the latest build number maybe useful before downloading the APK, so that people know that whether there is a newer update after the last download.

**Comment by andDevW** [comment]
With v3.2  the storage used is cut almost by half as laid out [here](https://github.com/andDevW/getChromium/issues/5). 
As for your third point, now that there is only the more exciting 'latest build', unless you're installing more than once daily there is a newer build available. **If you're still running the last known good build, you should switch to the updated latest build for safety and other reasons.**
The 1st point is the one that hasn't been addressed so I'll go ahead and include a more-accurate progress indicator with the next release.

**Comment by XyLoNaMiyX** [comment]
> show the percentage of download progress

I implemented this on #15. It doesn't show the %, but it shows a progress bar so you can still tell how much is left @EMK2000 :)

**Comment by andDevW** [comment]
Commented on [#15](https://github.com/andDevW/getChromium/pull/15).

**Comment by andDevW** [comment]
The package manager in Android O has a determinate installation progress bar, so I went ahead and accepted your pull request #15 in v4.1-beta-1. I'll add the delete APK feature and the build number feature into v4.1-beta-2.
