### ISSUE TITLE
Android 7.0 download error

### ISSUE THREAD

**Issue by computerinfo21** [andDevW/getChromium#16]
Cannot download on Android 7.0, gives error about exposed app through intent.getdata

Might be similar to http://stackoverflow.com/questions/38200282/android-os-fileuriexposedexception-file-storage-emulated-0-test-txt-exposed

**Comment by andDevW** [comment]
Thanks a million for the heads-up.
This will be fixed shortly, it's the top priority.

**Comment by computerinfo21** [comment]
Awesome! Thanks for the quick response! Hope it's not too hard to fix.

**Comment by computerinfo21** [comment]
Just tested with 3.2, to be sure and still had the error. Then updated to 3.5 and the error is gone and it installs properly! Thanks so much for fixing!
