### ISSUE TITLE
Hervey Castro from Google play store

### ISSUE THREAD

**Issue by hervey13** [andDevW/getChromium#19]
Hold on, copy/pasting...after this-> had an error btw using my default email address and couldn't sign up for this, I think I used it in the past and never used it again that's why..     

  Ops! I press edit and your link disappeared bro, I simply tried.... hard, I loved chromium on my Ubuntu PC, I think is simply stunning. Well I waited a long time for downloading the APK ZIP after i enabled the intended setting temporarily" & I got the unable to read parsed error message, idk. I got android version 5.1.1 I think, so I'm good? I can't switch my phone to recovery mode only restart, idk what cache I would have to delete, installing another browser instead of this one, I will defenetly come back for this 1 if it becomes a solid success, God I hope " you guys/deVs are amazing btw, shame on Firefox but 2 browsers are better than 1 also. " NO offense flame kitty/fox. "
  - btw I came back to Google play to check if the comment I posted had life, and luckily saw your reply again, that's why I'm here for you bro, yea. "

**Comment by andDevW** [comment]
Thanks for reaching out.
Anything over Android 4.4 works, so with 5.1.1 you should be good to go.
1. Boot into recovery mode and  wipe both **dalvik cache** and **cache**.  
**Be very careful not to wipe any of the other options listed.**  
2. Boot back into your device and try using getChromium again.
3. Everything should work, so let me know if it doesn't.

**Comment by hervey13** [comment]
I have no idea where that dalvik " cache is, I only know the normal cache my phone has, I don't have any options to boot in recovery I mentioned earlier, I only have when I long press the power button, shut down/ airplane mode & restart. I read this before though and idk nothing about it, had this phone for a good while and is my first and only android, but I know it very well anyway. :/

On Mar 27, 2017 6:11 PM, Andrew Wright <notifications@github.com> wrote:

Thanks for reaching out.
Anything over Android 4.4 works, so with 5.1.1 you should be good to go.

  1.  Boot into recovery mode and wipe both dalvik cache and cache.
Be very careful not to wipe any of the other options listed.
  2.  Boot back into your device and try using getChromium again.
  3.  Everything should work, so let me know if it doesn't.
