### ISSUE TITLE
Hervey Castro from Google play store #2

### ISSUE THREAD

**Issue by hervey13** [andDevW/getChromium#20]
I have no idea where that dalvik " cache is, I only know the normal cache my phone has, I don't have any options to boot in recovery I mentioned earlier, I only have when I long press the power button, shut down/ airplane mode & restart. I read this before though and idk nothing about it, had this phone for a good while and is my first and only android, but I know it very well anyway. :/

**Comment by hervey13** [comment]
Tried before... hooefully i could install Get" chromium.. someday.

**Comment by andDevW** [comment]
Are you running a custom ROM (like Cyanogenmod) that you didn't install?
The option to boot into recovery needs to be enabled under Settings > Developer Options, which could be hidden.

**Comment by andDevW** [comment]
Something's wrong with your phone.
There was one other issue just like yours https://github.com/andDevW/getChromium/issues/3
Not going to fix.
