### ISSUE TITLE
Feature Request: View installed and latest version

### ISSUE THREAD

**Issue by JeroenED** [andDevW/getChromium#26]
Hi,

I think it would be nice if within the gui we could see the last downloaded version and additionally the latest version available.

This way we have a indication of the installed version and updates rather than nothing.

I wouldn't mind if this would be generated from the url and just saved within the config rather than actually picking up from the APK

**Comment by andDevW** [comment]
Chromium has this built-in at chrome://version  
and a bunch of other useful URLs listed at chrome://chrome-urls    
I'll add info about the chrome-urls URL, but unless you're updating Chromium more than a few times daily each build version is newer than the previous build version.

**Comment by jkirk** [comment]
Yes. But it would be nice to see when the last version was installed - and if possible - to notify the user somehow if the currently version is "very" out of date.

If you think this is a reasonable idea, please consider re-opening this issue.
