### ISSUE TITLE
Parse error on Nexus 6P running Android 6.0.1

### ISSUE THREAD

**Issue by xiatianyu** [andDevW/getChromium#3]
As stated in the title, this prompt box popped up after the message "Downloading Chroming…" with a progress bar had been displaying for about 1 minute. 

![screenshot_20160327-102353](https://cloud.githubusercontent.com/assets/11317451/14080929/7aedf440-f53a-11e5-94cb-40275a739d47.png)

Let me know if any further information is required for debugging.

**Comment by andDevW** [comment]
Do you have 
Settings --> Security -->Unknown sources
set to **Allow installation of apps from sources other than the Play  Store**?

Other than that, make sure you have a good (WiFi) connection and try again. The download can take as long as several minutes.

**Comment by xiatianyu** [comment]
Yep, unknown sources are allowed. I've tested in several different places and on both Wi-Fi and LTE connections, but the problem persists. I also checked the app permission settings (introduced in Android 6.0) and none is shown to be required. Not sure if thay could be a problem. The Build Revision displayed by the app is 382014.

**Comment by xiatianyu** [comment]
I just tested this app on Nexus 7 (GSM, 2012 version) running Android 5.1.1 (CyanogenMod 12.1) and Galaxy Nexus running Android 4.4.4 (CyanogenMod 11). It worked on these two devices without any issues. Therefore, the problem seems to be Marshmallow-specific.

<img src="https://cloud.githubusercontent.com/assets/11317451/14124776/082454bc-f63a-11e5-9933-4f1ff61d46e0.png" width="320"> <img src="https://cloud.githubusercontent.com/assets/11317451/14124915/ddc2994e-f63a-11e5-83a8-5ad36b1115c6.png" width="320">
Upon further investigation, I noticed it doesn't ask for any access/permissions during installation on Android 6.0 (right), as opposed to its Android 4.4 counterpart (left). Now, it seems the culprit has been identified.

**Comment by andDevW** [comment]
I've tested it extensively on a Nexus 5 and a Nexus 6 (both on 6.0.1) with these setups: *AOSP(without gApps) 
*AOSP(with gApps)
*Stock Factory Images(with gApps)
No problems with any of the above configurations. 
Looks like it could be either a bug with the Nexus 6p specifically, or a bug with CM.

**Comment by xiatianyu** [comment]
@andDevW On my nexus 6P, I'm using the factory image with gApps included, so this is not a CM-specific bug.

**Comment by frazzmark** [comment]
Actually, the logcat is quite precise: the file is a folder.
![tmp_9068-_20160330_101316-636019292](https://cloud.githubusercontent.com/assets/7524830/14135903/58914e70-f660-11e5-95c8-3fa3dc4fc5ba.JPG)

**Comment by frazzmark** [comment]
And it's actually empty

**Comment by xiatianyu** [comment]
Curiously enough, the magic bullet is to reboot your device :sweat:.
@frazzmark Could you confirm this works for you?

**Comment by frazzmark** [comment]
@xiatianyu nope, it doesn't work. Still getting the same error.

**Comment by xiatianyu** [comment]
Now I can't seem to reproduce the problem again after the reboot, no matter what I do (i.e. uninstall and reinstall). :dizzy_face: Puzzling isn't it?

**Comment by andDevW** [comment]
Remember this trick next time you get an error(_any error_) - a simple reboot is often the solution.
Maybe it updated the Android security patch level with the reboot?
Glad you've got everything working.

**Comment by andDevW** [comment]
@frazzmark  is your CM up to date? It may be a bug on their end, and their bug-fixes are coming out nightly in some cases.

**Comment by frazzmark** [comment]
Yeah maybe it's been fixed from the source base. But I wouldn't like to install newer nightly because it's difficult for me to find a good build for my phone. This one I'm using is working well, when it gets very old I'll update it.
BTW I'm using the 20160325 nightly build.

**Comment by frazzmark** [comment]
@andDevW in a few days I'll get another phone running cm 13 and I'll try on that device.

**Comment by cjleighton** [comment]
I'm also having this issue. I looked in the data folder, and the only files being downloaded are ContentShell.apk and some .tmp files.

Droid Turbo, Android 5.1.

**Comment by andDevW** [comment]
Did you reboot/update your phone?
If not, then reboot and if possible, update.

**Comment by cjleighton** [comment]
I've rebooted, no changes.

**Comment by GuilleDF** [comment]
I have the same problem on my nexus 5 running cm13 and rebooting doesn't fix it. I'm running today's nightly, should I try to update tomorrow to the next one?

**Comment by andDevW** [comment]
Maybe a non-nightly release would be less buggy?
It's starting to look like this is an issue with CM, have you submitted any bug reports to them?

**Comment by xiatianyu** [comment]
I'd like to reiterate that the bug in question is unlikely to be peculiar to CyanogenMod, since I was **NOT** using CM when I encountered the error. On a side note, the Android security patch level was not upgraded with my reboot, as it is still on ``1 March 2016`` right now.
@cjleighton Are you running CyanogenMod on your Droid Turbo too?

**Comment by andDevW** [comment]
But a reboot fixed your problem, and it sounds like this is not the case with the phones running CM.
CM has a recovery,  @GuilleDF @cjleighton @frazzmark, if you boot into recovery there is an option to "wipe cache-partition" and "wipe dalvik partition". It's a good idea to wipe those partitions after any install or update. Try wiping these partitions.

**Comment by GuilleDF** [comment]
I've updated to the next nightly and wiped dalvik & cache, and everytihng seems to be working. It sounds like you were right, @andDevW. I guess I'll get accustomed to wiping those after each upgrade.

**Comment by andDevW** [comment]
Excellent, glad you've got it sorted.

**Comment by frazzmark** [comment]
@andDevW I just reinstalled the cyanogenmod, and now it works! Chromium installs fine. Also I tried on another device with cyanogenmod 13 and it doesn't have any problems.

**Comment by andDevW** [comment]
Good to see you've got it working.
