### ISSUE TITLE
Problem with downloading Chromium

### ISSUE THREAD

**Issue by ghost** [andDevW/getChromium#31]
Hello,

Today I have installed getChromium app from FDroid store, to download and install Chromium for Android.

When downloading Chromium via getChromium I got this error:
![Screenshot_20200117-123159](https://user-images.githubusercontent.com/503963/72610364-6f2dc600-3927-11ea-946c-697e379f458d.png)

btw,
In In Android 9 and higher checkbox "install apps from unknow sources" where moved from system settings to apps. In getChromium app I dont have this settings to enable :/

Trying on:
Nokia 7+
Android 10

**Comment by travisfw** [comment]
Also true on Galaxy Tab S6, Android 10, and has been true for months. Because of this issue, I'm just not using Chromium.

**Comment by andDevW** [comment]
It throws the exact same error on Android 11 beta.
Working on a patch now.
In the meantime you can download Chromium APK from the official download page:
[https://download-chromium.appspot.com/](https://download-chromium.appspot.com/)

**Comment by geraldo** [comment]
Same problem here with getcrhomium 4.1 on Android 10. Direct install of apk works fine.

**Comment by toumbo** [comment]
The issue persists! I'm on android 10

**Comment by andDevW** [comment]
This isn't going to work on anything above Android 8.
