### ISSUE TITLE
Info about the chromium source

### ISSUE THREAD

**Issue by monojp** [andDevW/getChromium#4]
Hi, I'm missing info about the chromium source this app uses. It is downloading an apk file I guess? Could you please state where you get it from?
Regards

**Comment by jonasdemoor** [comment]
I checked the Java source and it seems the app downloads the latest Chromium version from googleapis.com. So I think there's nothing to worry about.

Developer, would you add more information about what the app exactly does to the description please? :)

**Comment by andDevW** [comment]
You're exactly right, it downloads the most recent "Last Known Good Revision" directly from [https://commondatastorage.googleapis.com/chromium-browser-continuous/](https://commondatastorage.googleapis.com/chromium-browser-continuous/). It retrieves a zip file named "chrome-android.zip" which contains the "ChromePublic.apk" (Chromium).  For more information about Chromium: [https://www.chromium.org/Home](https://www.chromium.org/Home).
