### ISSUE TITLE
Please make it clear it is an unstable version

### ISSUE THREAD

**Issue by realdmitchell** [andDevW/getChromium#6]
Just nitpicking. As far as I understand this auto-built Chromium "as right off the trunk. It may be tremendously buggy". Please put this info in the main page of the app. 

Thanks for the great work.
[1]. https://download-chromium.appspot.com/?platform=Android&type=snapshots

**Comment by andDevW** [comment]
Good looking out, I went ahead and added the warning.
Next release will include the warning in the app as well.
