### ISSUE TITLE
Choose between 'Latest' and 'Last Known Good Revision'

### ISSUE THREAD

**Issue by zeorin** [andDevW/getChromium#9]
If you go to http://getchromium.com/ and click on 'Chromium for Android' at the bottom right, one can download the latest build 'right off the trunk', or the last known good revision. Many users might like to download the last known good revision instead of the absolute bleeding edge.

Would it be possible to add this option to the getChromium app also?

**Comment by andDevW** [comment]
Not a problem, I'll add an option to install the "latest" build in the next release.
